<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7fc59fa1-9723-49aa-9ec7-c727d305a35b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.69" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
    <PackageReference Include="Microsoft.ML" Version="4.0.1" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

</Project>
